### ISSUE TITLE
Proceeds with installation by itself

### ISSUE THREAD

**Issue by jaasio** [crystal-linux/citrine#2] opened 2021-06-08 13:50 UTC
Asks for input but proceeds without it 

THis happens on the choose DE step of installation

![Screenshot 2021-06-08 at 15 47 13](https://user-images.githubusercontent.com/54361578/121196770-0b37d480-c871-11eb-8831-5190ea7a00a9.png)

**Comment by SomethingGeneric** [comment] 2021-06-08 13:51
That's actually not a bug since we're calling pacman with `--noconfirm`. Gonne leave this as a to-do to silence pacman prompts with `::` tho

**Comment by SomethingGeneric** [comment] 2021-07-18 01:24
So turns out that commit didn't help. @jnats any ideas besides just `--quiet` ?

**Comment by SomethingGeneric** [comment] 2021-10-07 15:42
@jnats stale issue moment. any ideas?

**Comment by axtloss** [comment] 2021-10-07 15:44
sorry, didnt mean to close it

**Comment by jnats** [comment] 2021-10-08 07:27
`sudo pacman -Sq --noconfirm package | grep "^[^::]" ` could help but it also messes up the output slightly (no progress bars come up and colour codes dont make it through either
![image](https://user-images.githubusercontent.com/30374463/136515591-1bae6d57-33f4-4214-8b78-8e55e1c5fdeb.png)

**Closed** 2021-10-10 20:43 UTC
Labels: enhancement, help wanted
